
CREATE DATABASE IF NOT EXISTS TP10 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE TP10;
CREATE TABLE IF NOT EXISTS exercice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(255) NOT NULL,
    auteur VARCHAR(255) NOT NULL,
    date_creation DATE NOT NULL
);
